# -*- coding: utf-8 -*-
"""Assessment1_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wt9aTTL1lVeJQ_rSZCE-c_mmIG77LBLi

Connect Google Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""Import libraries"""

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from skimage.feature import local_binary_pattern, hog

"""Write functions to load and process data"""

# Haar Cascade face detection
face_cascade = cv2.CascadeClassifier('/content/drive/MyDrive/haarcascade_frontalface_default.xml')

def load_and_detect_faces(folder_path):
    images, labels = [], []
    for label in os.listdir(folder_path):
        label_path = os.path.join(folder_path, label)
        if os.path.isdir(label_path):
            for img_file in os.listdir(label_path):
                img_path = os.path.join(label_path, img_file)
                img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
                if img is not None:
                    faces = face_cascade.detectMultiScale(img, scaleFactor=1.1, minNeighbors=5, minSize=(30,30))
                    for (x,y,w,h) in faces:
                        face_region = img[y:y+h, x:x+w]
                        images.append(face_region)
                        labels.append(label)
    return images, labels

"""Features (LBP and HOG)"""

# version 0
def extract_lbp_features(images, radius=1):
    n_points = 8 * radius
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        lbp = local_binary_pattern(img, n_points, radius, method="uniform")
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, n_points+3), range=(0, n_points+2))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-6)
        features.append(hist)
    return np.array(features)

def extract_hog_features(images):
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        hog_feat = hog(img, orientations=8, pixels_per_cell=(8,8),
                       cells_per_block=(2,2), block_norm='L2-Hys')
        features.append(hog_feat)
    return np.array(features)

# version 1
# more detailed LBP and HOG
def extract_lbp_features_v1(images, radius=2):
    n_points = 8 * radius
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        lbp = local_binary_pattern(img, n_points, radius, method="uniform")
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, n_points+3), range=(0, n_points+2))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-6)
        features.append(hist)
    return np.array(features)

def extract_hog_features_v1(images):
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        hog_feat = hog(img, orientations=9, pixels_per_cell=(8,8),
                       cells_per_block=(3,3), block_norm='L2-Hys')
        features.append(hog_feat)
    return np.array(features)

# version 2
# larger blocks and radius
def extract_lbp_features_v2(images, radius=3):
    n_points = 8 * radius
    features = []
    for img in images:
        img = cv2.resize(img, (128,128))  # bigger image
        lbp = local_binary_pattern(img, n_points, radius, method="uniform")
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, n_points+3), range=(0, n_points+2))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-6)
        features.append(hist)
    return np.array(features)

def extract_hog_features_v2(images):
    features = []
    for img in images:
        img = cv2.resize(img, (128,128))  # bigger image
        hog_feat = hog(img, orientations=12, pixels_per_cell=(16,16),
                       cells_per_block=(2,2), block_norm='L2-Hys')
        features.append(hog_feat)
    return np.array(features)

# version 3
# Small cells for HOG and combined LBP
def extract_lbp_features_v3(images, radius=2):
    n_points = 8 * radius
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        lbp = local_binary_pattern(img, n_points, radius, method="uniform")
        hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, n_points+3), range=(0, n_points+2))
        hist = hist.astype("float")
        hist /= (hist.sum() + 1e-6)
        features.append(hist)
    return np.array(features)

def extract_hog_features_v3(images):
    features = []
    for img in images:
        img = cv2.resize(img, (64,64))
        hog_feat = hog(img, orientations=9, pixels_per_cell=(4,4),
                       cells_per_block=(2,2), block_norm='L2-Hys')
        features.append(hog_feat)
    return np.array(features)

"""Training and evaluation of models"""

def train_and_evaluate(X_train, y_train, X_test, y_test, model, model_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"{model_name} Accuracy: {acc*100:.2f}%")
    print(classification_report(y_test, y_pred))

    conf_matrix = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(6,6))
    sns.heatmap(conf_matrix, annot=True, fmt="d", cmap="Blues")
    plt.title(f"{model_name} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.show()

"""Main launch"""

train_path = "/content/drive/MyDrive/CK_dataset/train"
test_path = "/content/drive/MyDrive/CK_dataset/test"

X_train_faces, y_train = load_and_detect_faces(train_path)
X_test_faces, y_test = load_and_detect_faces(test_path)

X_train_lbp = extract_lbp_features_v3(X_train_faces) # extract_lpb_features_v1,extract_hog_features_v2,extract_hog_features_v3
X_test_lbp = extract_lbp_features_v3(X_test_faces)   # extract_lpb_features_v1,extract_hog_features_v2,extract_hog_features_v3

X_train_hog = extract_hog_features_v3(X_train_faces) # extract_hog_features_v1,extract_hog_features_v2,extract_hog_features_v3
X_test_hog = extract_hog_features_v3(X_test_faces)   # extract_hog_features_v1,extract_hog_features_v2,extract_hog_features_v3

train_and_evaluate(X_train_lbp, y_train, X_test_lbp, y_test, SVC(kernel='rbf', C=7, gamma='scale'), "SVM (LBP)")
train_and_evaluate(X_train_lbp, y_train, X_test_lbp, y_test, DecisionTreeClassifier(max_depth=10), "Decision Tree (LBP)")
train_and_evaluate(X_train_hog, y_train, X_test_hog, y_test, KNeighborsClassifier(n_neighbors=5), "KNN (HOG)")
train_and_evaluate(X_train_hog, y_train, X_test_hog, y_test, GaussianNB(), "Naive Bayes (HOG)")

"""Test on one image"""

def predict_single_image(image_path, model, feature_type="LBP"):
    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    if img is None:
        print("Error: image not found at path", image_path)
        return

    faces = face_cascade.detectMultiScale(img, scaleFactor=1.1, minNeighbors=5, minSize=(30,30))
    if len(faces) == 0:
        print("No face detected in the image")
        return

    for (x,y,w,h) in faces:
        face_region = img[y:y+h, x:x+w]

        # Use version 3
        if feature_type == "LBP":
            features = extract_lbp_features_v3([face_region], radius=2)
        elif feature_type == "HOG":
            features = extract_hog_features_v3([face_region])
        else:
            print("Unknown feature type:", feature_type)
            return

        # Prediction
        pred = model.predict(features)[0]
        print(f"Predicted Emotion: {pred}")

        # Visualization
        img_color = cv2.imread(image_path)
        img_color = cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB)
        cv2.rectangle(img_color, (x,y), (x+w,y+h), (255,0,0), 2)
        cv2.putText(img_color, pred, (x,y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255,0,0), 2)

        plt.figure(figsize=(6,6))
        plt.imshow(img_color)
        plt.axis('off')
        plt.title(f"Predicted Emotion: {pred}")
        plt.show()

image_path = "/content/drive/MyDrive/CK_dataset/test/anger/0.jpg"

# 1. SVM с LBP
predict_single_image(
    image_path,
    SVC(kernel='rbf', C=7, gamma='scale').fit(X_train_lbp, y_train),
    feature_type="LBP"
)

# 2. Decision Tree с LBP
predict_single_image(
    image_path,
    DecisionTreeClassifier(max_depth=10, random_state=42).fit(X_train_lbp, y_train),
    feature_type="LBP"
)

# 3. KNN с HOG
predict_single_image(
    image_path,
    KNeighborsClassifier(n_neighbors=5).fit(X_train_hog, y_train),
    feature_type="HOG"
)

# 4. Naive Bayes с HOG
predict_single_image(
    image_path,
    GaussianNB().fit(X_train_hog, y_train),
    feature_type="HOG"
)

